/*
 * API Settings
 * At BlueSnap, we look at payments a little differently. Our Payment Orchestration Platform helps businesses accept payments globally and is designed to increase revenue and reduces costs. We provide a comprehensive back-end solutions that simplifies the complexity of payments, managing the full process from start to finish.  BlueSnap supports payments through multiple sales channels such as online and mobile sales, marketplaces, subscriptions, invoice payments and manual orders through a virtual terminal. And for businesses looking for embedded payments, we offer white-labeled payments for platforms with automated underwriting and onboarding that supports marketplaces and split payments.  And with one integration and contract, businesses can sell in over 200 geographies with access to local acquiring in 47 countries, 110+ currencies and 100+ global payment types, including popular eWallets, automated accounts receivable, world-class fraud protection and chargeback management, built-in solutions for regulation and tax compliance, and unified global reporting to help businesses grow.  With a US headquarters in Waltham, MA, and EU headquarters in Dublin, Ireland, BlueSnap is backed by world-class private equity investors including Great Hill Partners and Parthenon Capital Partners.   Learn more at BlueSnap.com
 *
 * The version of the OpenAPI document: 8976-Tools
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.VendorUpdateVendorRequestPayoutInfoInner;
import com.konfigthis.client.model.VendorUpdateVendorRequestVendorAgreement;
import com.konfigthis.client.model.VendorUpdateVendorRequestVendorPrincipal;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for VendorUpdateVendorRequest
 */
public class VendorUpdateVendorRequestTest {
    private final VendorUpdateVendorRequest model = new VendorUpdateVendorRequest();

    /**
     * Model tests for VendorUpdateVendorRequest
     */
    @Test
    public void testVendorUpdateVendorRequest() {
        // TODO: test VendorUpdateVendorRequest
    }

    /**
     * Test the property 'email'
     */
    @Test
    public void emailTest() {
        // TODO: test email
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'firstName'
     */
    @Test
    public void firstNameTest() {
        // TODO: test firstName
    }

    /**
     * Test the property 'lastName'
     */
    @Test
    public void lastNameTest() {
        // TODO: test lastName
    }

    /**
     * Test the property 'address'
     */
    @Test
    public void addressTest() {
        // TODO: test address
    }

    /**
     * Test the property 'city'
     */
    @Test
    public void cityTest() {
        // TODO: test city
    }

    /**
     * Test the property 'zip'
     */
    @Test
    public void zipTest() {
        // TODO: test zip
    }

    /**
     * Test the property 'country'
     */
    @Test
    public void countryTest() {
        // TODO: test country
    }

    /**
     * Test the property 'phone'
     */
    @Test
    public void phoneTest() {
        // TODO: test phone
    }

    /**
     * Test the property 'state'
     */
    @Test
    public void stateTest() {
        // TODO: test state
    }

    /**
     * Test the property 'taxId'
     */
    @Test
    public void taxIdTest() {
        // TODO: test taxId
    }

    /**
     * Test the property 'vendorUrl'
     */
    @Test
    public void vendorUrlTest() {
        // TODO: test vendorUrl
    }

    /**
     * Test the property 'ipnUrl'
     */
    @Test
    public void ipnUrlTest() {
        // TODO: test ipnUrl
    }

    /**
     * Test the property 'defaultPayoutCurrency'
     */
    @Test
    public void defaultPayoutCurrencyTest() {
        // TODO: test defaultPayoutCurrency
    }

    /**
     * Test the property 'vendorPrincipal'
     */
    @Test
    public void vendorPrincipalTest() {
        // TODO: test vendorPrincipal
    }

    /**
     * Test the property 'payoutInfo'
     */
    @Test
    public void payoutInfoTest() {
        // TODO: test payoutInfo
    }

    /**
     * Test the property 'vendorAgreement'
     */
    @Test
    public void vendorAgreementTest() {
        // TODO: test vendorAgreement
    }

}
