/*
 * API Settings
 * At BlueSnap, we look at payments a little differently. Our Payment Orchestration Platform helps businesses accept payments globally and is designed to increase revenue and reduces costs. We provide a comprehensive back-end solutions that simplifies the complexity of payments, managing the full process from start to finish.  BlueSnap supports payments through multiple sales channels such as online and mobile sales, marketplaces, subscriptions, invoice payments and manual orders through a virtual terminal. And for businesses looking for embedded payments, we offer white-labeled payments for platforms with automated underwriting and onboarding that supports marketplaces and split payments.  And with one integration and contract, businesses can sell in over 200 geographies with access to local acquiring in 47 countries, 110+ currencies and 100+ global payment types, including popular eWallets, automated accounts receivable, world-class fraud protection and chargeback management, built-in solutions for regulation and tax compliance, and unified global reporting to help businesses grow.  With a US headquarters in Waltham, MA, and EU headquarters in Dublin, Ireland, BlueSnap is backed by world-class private equity investors including Great Hill Partners and Parthenon Capital Partners.   Learn more at BlueSnap.com
 *
 * The version of the OpenAPI document: 8976-Tools
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * TransactionCreateSofortTransactionRequestBecsDirectDebitTransaction
 */@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class TransactionCreateSofortTransactionRequestBecsDirectDebitTransaction {
  public static final String SERIALIZED_NAME_BSB_NUMBER = "bsbNumber";
  @SerializedName(SERIALIZED_NAME_BSB_NUMBER)
  private String bsbNumber = "980201";

  public static final String SERIALIZED_NAME_ACCOUNT_NUMBER = "accountNumber";
  @SerializedName(SERIALIZED_NAME_ACCOUNT_NUMBER)
  private String accountNumber = "9990000001";

  public static final String SERIALIZED_NAME_ACCOUNT_NAME = "accountName";
  @SerializedName(SERIALIZED_NAME_ACCOUNT_NAME)
  private String accountName = "Boris Britva";

  public static final String SERIALIZED_NAME_FINANCIAL_INSTITUTION = "financialInstitution";
  @SerializedName(SERIALIZED_NAME_FINANCIAL_INSTITUTION)
  private String financialInstitution = "financialInstitution";

  public static final String SERIALIZED_NAME_BRANCH_NAME = "branchName";
  @SerializedName(SERIALIZED_NAME_BRANCH_NAME)
  private String branchName = "branchName";

  public static final String SERIALIZED_NAME_AGREEMENT_ID = "agreementId";
  @SerializedName(SERIALIZED_NAME_AGREEMENT_ID)
  private Integer agreementId = 81;

  public TransactionCreateSofortTransactionRequestBecsDirectDebitTransaction() {
  }

  public TransactionCreateSofortTransactionRequestBecsDirectDebitTransaction bsbNumber(String bsbNumber) {
    
    
    
    
    this.bsbNumber = bsbNumber;
    return this;
  }

   /**
   * Get bsbNumber
   * @return bsbNumber
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "980201", value = "")

  public String getBsbNumber() {
    return bsbNumber;
  }


  public void setBsbNumber(String bsbNumber) {
    
    
    
    this.bsbNumber = bsbNumber;
  }


  public TransactionCreateSofortTransactionRequestBecsDirectDebitTransaction accountNumber(String accountNumber) {
    
    
    
    
    this.accountNumber = accountNumber;
    return this;
  }

   /**
   * Get accountNumber
   * @return accountNumber
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "9990000001", value = "")

  public String getAccountNumber() {
    return accountNumber;
  }


  public void setAccountNumber(String accountNumber) {
    
    
    
    this.accountNumber = accountNumber;
  }


  public TransactionCreateSofortTransactionRequestBecsDirectDebitTransaction accountName(String accountName) {
    
    
    
    
    this.accountName = accountName;
    return this;
  }

   /**
   * Get accountName
   * @return accountName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "Boris Britva", value = "")

  public String getAccountName() {
    return accountName;
  }


  public void setAccountName(String accountName) {
    
    
    
    this.accountName = accountName;
  }


  public TransactionCreateSofortTransactionRequestBecsDirectDebitTransaction financialInstitution(String financialInstitution) {
    
    
    
    
    this.financialInstitution = financialInstitution;
    return this;
  }

   /**
   * Get financialInstitution
   * @return financialInstitution
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "financialInstitution", value = "")

  public String getFinancialInstitution() {
    return financialInstitution;
  }


  public void setFinancialInstitution(String financialInstitution) {
    
    
    
    this.financialInstitution = financialInstitution;
  }


  public TransactionCreateSofortTransactionRequestBecsDirectDebitTransaction branchName(String branchName) {
    
    
    
    
    this.branchName = branchName;
    return this;
  }

   /**
   * Get branchName
   * @return branchName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "branchName", value = "")

  public String getBranchName() {
    return branchName;
  }


  public void setBranchName(String branchName) {
    
    
    
    this.branchName = branchName;
  }


  public TransactionCreateSofortTransactionRequestBecsDirectDebitTransaction agreementId(Integer agreementId) {
    
    
    
    
    this.agreementId = agreementId;
    return this;
  }

   /**
   * Get agreementId
   * @return agreementId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "81", value = "")

  public Integer getAgreementId() {
    return agreementId;
  }


  public void setAgreementId(Integer agreementId) {
    
    
    
    this.agreementId = agreementId;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the TransactionCreateSofortTransactionRequestBecsDirectDebitTransaction instance itself
   */
  public TransactionCreateSofortTransactionRequestBecsDirectDebitTransaction putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TransactionCreateSofortTransactionRequestBecsDirectDebitTransaction transactionCreateSofortTransactionRequestBecsDirectDebitTransaction = (TransactionCreateSofortTransactionRequestBecsDirectDebitTransaction) o;
    return Objects.equals(this.bsbNumber, transactionCreateSofortTransactionRequestBecsDirectDebitTransaction.bsbNumber) &&
        Objects.equals(this.accountNumber, transactionCreateSofortTransactionRequestBecsDirectDebitTransaction.accountNumber) &&
        Objects.equals(this.accountName, transactionCreateSofortTransactionRequestBecsDirectDebitTransaction.accountName) &&
        Objects.equals(this.financialInstitution, transactionCreateSofortTransactionRequestBecsDirectDebitTransaction.financialInstitution) &&
        Objects.equals(this.branchName, transactionCreateSofortTransactionRequestBecsDirectDebitTransaction.branchName) &&
        Objects.equals(this.agreementId, transactionCreateSofortTransactionRequestBecsDirectDebitTransaction.agreementId)&&
        Objects.equals(this.additionalProperties, transactionCreateSofortTransactionRequestBecsDirectDebitTransaction.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(bsbNumber, accountNumber, accountName, financialInstitution, branchName, agreementId, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TransactionCreateSofortTransactionRequestBecsDirectDebitTransaction {\n");
    sb.append("    bsbNumber: ").append(toIndentedString(bsbNumber)).append("\n");
    sb.append("    accountNumber: ").append(toIndentedString(accountNumber)).append("\n");
    sb.append("    accountName: ").append(toIndentedString(accountName)).append("\n");
    sb.append("    financialInstitution: ").append(toIndentedString(financialInstitution)).append("\n");
    sb.append("    branchName: ").append(toIndentedString(branchName)).append("\n");
    sb.append("    agreementId: ").append(toIndentedString(agreementId)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("bsbNumber");
    openapiFields.add("accountNumber");
    openapiFields.add("accountName");
    openapiFields.add("financialInstitution");
    openapiFields.add("branchName");
    openapiFields.add("agreementId");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to TransactionCreateSofortTransactionRequestBecsDirectDebitTransaction
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!TransactionCreateSofortTransactionRequestBecsDirectDebitTransaction.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in TransactionCreateSofortTransactionRequestBecsDirectDebitTransaction is not found in the empty JSON string", TransactionCreateSofortTransactionRequestBecsDirectDebitTransaction.openapiRequiredFields.toString()));
        }
      }
      if ((jsonObj.get("bsbNumber") != null && !jsonObj.get("bsbNumber").isJsonNull()) && !jsonObj.get("bsbNumber").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `bsbNumber` to be a primitive type in the JSON string but got `%s`", jsonObj.get("bsbNumber").toString()));
      }
      if ((jsonObj.get("accountNumber") != null && !jsonObj.get("accountNumber").isJsonNull()) && !jsonObj.get("accountNumber").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `accountNumber` to be a primitive type in the JSON string but got `%s`", jsonObj.get("accountNumber").toString()));
      }
      if ((jsonObj.get("accountName") != null && !jsonObj.get("accountName").isJsonNull()) && !jsonObj.get("accountName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `accountName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("accountName").toString()));
      }
      if ((jsonObj.get("financialInstitution") != null && !jsonObj.get("financialInstitution").isJsonNull()) && !jsonObj.get("financialInstitution").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `financialInstitution` to be a primitive type in the JSON string but got `%s`", jsonObj.get("financialInstitution").toString()));
      }
      if ((jsonObj.get("branchName") != null && !jsonObj.get("branchName").isJsonNull()) && !jsonObj.get("branchName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `branchName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("branchName").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!TransactionCreateSofortTransactionRequestBecsDirectDebitTransaction.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'TransactionCreateSofortTransactionRequestBecsDirectDebitTransaction' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<TransactionCreateSofortTransactionRequestBecsDirectDebitTransaction> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(TransactionCreateSofortTransactionRequestBecsDirectDebitTransaction.class));

       return (TypeAdapter<T>) new TypeAdapter<TransactionCreateSofortTransactionRequestBecsDirectDebitTransaction>() {
           @Override
           public void write(JsonWriter out, TransactionCreateSofortTransactionRequestBecsDirectDebitTransaction value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public TransactionCreateSofortTransactionRequestBecsDirectDebitTransaction read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             TransactionCreateSofortTransactionRequestBecsDirectDebitTransaction instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of TransactionCreateSofortTransactionRequestBecsDirectDebitTransaction given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of TransactionCreateSofortTransactionRequestBecsDirectDebitTransaction
  * @throws IOException if the JSON string is invalid with respect to TransactionCreateSofortTransactionRequestBecsDirectDebitTransaction
  */
  public static TransactionCreateSofortTransactionRequestBecsDirectDebitTransaction fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, TransactionCreateSofortTransactionRequestBecsDirectDebitTransaction.class);
  }

 /**
  * Convert an instance of TransactionCreateSofortTransactionRequestBecsDirectDebitTransaction to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

