/*
 * API Settings
 * At BlueSnap, we look at payments a little differently. Our Payment Orchestration Platform helps businesses accept payments globally and is designed to increase revenue and reduces costs. We provide a comprehensive back-end solutions that simplifies the complexity of payments, managing the full process from start to finish.  BlueSnap supports payments through multiple sales channels such as online and mobile sales, marketplaces, subscriptions, invoice payments and manual orders through a virtual terminal. And for businesses looking for embedded payments, we offer white-labeled payments for platforms with automated underwriting and onboarding that supports marketplaces and split payments.  And with one integration and contract, businesses can sell in over 200 geographies with access to local acquiring in 47 countries, 110+ currencies and 100+ global payment types, including popular eWallets, automated accounts receivable, world-class fraud protection and chargeback management, built-in solutions for regulation and tax compliance, and unified global reporting to help businesses grow.  With a US headquarters in Waltham, MA, and EU headquarters in Dublin, Ireland, BlueSnap is backed by world-class private equity investors including Great Hill Partners and Parthenon Capital Partners.   Learn more at BlueSnap.com
 *
 * The version of the OpenAPI document: 8976-Tools
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.Configuration;
import com.konfigthis.client.model.ShopperCreateVaultedShopperRequest;
import com.konfigthis.client.model.ShopperCreateVaultedShopperRequestPaymentSources;
import com.konfigthis.client.model.ShopperUpdateVaultedShopperRequest;
import com.konfigthis.client.model.ShopperUpdateVaultedShopperRequestPaymentSources;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeAll;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ShopperApi
 */
@Disabled
public class ShopperApiTest {

    private static ShopperApi api;

    
    @BeforeAll
    public static void beforeClass() {
        ApiClient apiClient = Configuration.getDefaultApiClient();
        api = new ShopperApi(apiClient);
    }

    /**
     * Create Vaulted Shopper
     *
     * 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createVaultedShopperTest() throws ApiException {
        ShopperCreateVaultedShopperRequestPaymentSources paymentSources = null;
        String firstName = null;
        String lastName = null;
        api.createVaultedShopper()
                .paymentSources(paymentSources)
                .firstName(firstName)
                .lastName(lastName)
                .execute();
        // TODO: test validations
    }

    /**
     * Delete Vaulted Shopper
     *
     * 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void deleteVaultedShopperTest() throws ApiException {
        String vaultedShopperId = null;
        api.deleteVaultedShopper(vaultedShopperId)
                .execute();
        // TODO: test validations
    }

    /**
     * Retrieve Vaulted Shopper
     *
     * 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getTest() throws ApiException {
        String vaultedShopperId = null;
        api.get(vaultedShopperId)
                .execute();
        // TODO: test validations
    }

    /**
     * Update Vaulted Shopper
     *
     * 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updateVaultedShopperTest() throws ApiException {
        String vaultedShopperId = null;
        ShopperUpdateVaultedShopperRequestPaymentSources paymentSources = null;
        String firstName = null;
        String lastName = null;
        api.updateVaultedShopper(vaultedShopperId)
                .paymentSources(paymentSources)
                .firstName(firstName)
                .lastName(lastName)
                .execute();
        // TODO: test validations
    }

}
